### ISSUE TITLE
All "Bug fixes" links go to first "bugfixes" link on the page

### ISSUE THREAD

**Issue by corfe83** [ebitengine/ebitengine.org#12]
If I click on bugfixes for 2.4.9 (as in screenshot), I expect it to go to bugfixes for 2.4.9. It goes to bugfixes for 2.4.0, because every release's "bugfixes" link is the same link, instead of each being different.

https://ebitengine.org/en/documents/2.4.html

![image](https://user-images.githubusercontent.com/61067263/199274965-5accba60-7bbd-4695-b052-3f5f296c257e.png)

**Comment by hajimehoshi** [comment]
Thank you for reporting!
