### ISSUE TITLE
Typo in the matrix multiplication using three-dimensions example

### ISSUE THREAD

**Issue by RyHig** [ebitengine/ebitengine.org#13]
in the following html page https://ebitengine.org/en/documents/matrix.html there is a typo.

https://github.com/ebitengine/ebitengine.org/blob/e8db9293ab253eb50318f883003cb65d660cd3a3/contents/en/documents/matrix.html#L235-L237

The last product of the sum in the first column should be multiplied by `g_1` not `d_1`.

```
  a_2 a_1 + b_2 d_1 + c_2 g_1 & a_2 b_1 + b_2 e_1 + c_2 h_1 & a_2 c_1 + b_2 f_1 + c_2 i_1 \\
  d_2 a_1 + e_2 d_1 + f_2 g_1 & d_2 b_1 + e_2 e_1 + f_2 h_1 & d_2 c_1 + e_2 f_1 + f_2 i_1 \\
  g_2 a_1 + h_2 d_1 + i_2 g_1 & g_2 b_1 + h_2 e_1 + i_2 h_1 & g_2 c_1 + h_2 f_1 + i_2 i_1 \\
```

**Comment by hajimehoshi** [comment]
Thanks!
