### ISSUE TITLE
Published Git conflict 

### ISSUE THREAD

**Issue by kefniark** [ebitengine/ebitengine.org#18]
## Description
Looks like some unresolved git conflict end up on the website 😄 

https://ebiten-zh.vercel.app/documents/install.html

```html
<<<<<<< HEAD
...
=======
...
>>>>>>> a88ba8e8aeb239a2a2a9121f75c24c2d7da302a7
```

**Comment by hajimehoshi** [comment]
This is not managed by me but by @EldersJavas

**Comment by kefniark** [comment]
Sorry my bad, look so similar I didn't even realized it was a separated domain name managed by someone else 😄
