### ISSUE TITLE
ebitengine.org/en/tour/hello_world.html stale go imports

### ISSUE THREAD

**Issue by sprive** [ebitengine/ebitengine.org#20]
https://ebitengine.org/en/tour/hello_world.html

After creating `main.go` and pasting in the tour's code, I get:

```
ebiten_helloworld % go run main.go
main.go:6:2: no required module provides package github.com/hajimehoshi/ebiten/v2: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:7:2: no required module provides package github.com/hajimehoshi/ebiten/v2/ebitenutil: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

I'm not a Go expert but I can see the tutorlal's URLs point to old modules that no longer exist (404 in my browser).
I'm just not sure what to replace with.

----
What's odd is if I go to:
https://ebitengine.org/en/examples/animation.html

and then run `go run github.com/hajimehoshi/ebiten/v2/examples/animation@latest`
it works... despite pulling in the same ebiten library URLs.

**Comment by hajimehoshi** [comment]
I'll update the document but

> go.mod file not found 

This is it. Try `go mod init foo && go mod tidy` and then `go run main.go`.
