### ISSUE TITLE
Error in Hello World code 

### ISSUE THREAD

**Issue by oaklandgit** [ebitengine/ebitengine.org#27]
On: https://ebitengine.org/en/tour/hello_world.html

I believe this line 
```
func (g *Game) Update() error {
	return nil
}
```

should be:

```
func (g *Game) Update(*ebiten.Image) error {
	return nil
}
```

For me, it wouldn't compile without that change.

**Comment by hajimehoshi** [comment]
I guess you are using v1 (`github.com/hajimehoshi/ebiten`), not v2 (`github.com/hajimehoshi/ebiten/v2`)
