### ISSUE TITLE
Microphone input

### ISSUE THREAD

**Issue by robrohan** [ebitengine/ebitengine.org#28]
My apologies if this already exists, I just can't seem to find it in the examples / documentation.

Does ebitengine have a way to get microphone input? I am doing a spike for a game and we like ebitengine so far, but part of the spike requires processing some microphone input.

If it currently does not support it, do you have any suggestions on where / how to add it if I was to attempt to add it?

**Comment by hajimehoshi** [comment]
This repository is for the website, not Ebitengine.

> Does ebitengine have a way to get microphone input?

No, Ebitengine doesn't have the microphone input. If you have a request, please file an isssue.

**Comment by robrohan** [comment]
Apologies for posting to the wrong repo - but thanks for the info
