### ISSUE TITLE
Documents/Features/Shader: Outdated example

### ISSUE THREAD

**Issue by aoyako** [ebitengine/ebitengine.org#29]
An example of shader [features](https://ebitengine.org/en/documents/shader.html#Example) should? contain the same code as for the `lighting.go` shader, but it is different, and no instructions are provided on how to run/use it.

The original `lighting.go` was changed a few times:
https://github.com/hajimehoshi/ebiten/issues/2638
https://github.com/hajimehoshi/ebiten/issues/2767

If possible, linking the shader directly to the webpage would solve future issues on this page.

**Comment by hajimehoshi** [comment]
Thanks!
