### ISSUE TITLE
Consoles 

### ISSUE THREAD

**Issue by gedw99** [ebitengine/ebitengine.org#33]
https://ebitengine.org/en/blog/nintendo_switch.html

a tone know the OS and Graphics requirements for this and PlayStation and Microsoft ?

I hrard  the OS is FreeBSD . Not sure if the graphics layer is SDL .

**Comment by hajimehoshi** [comment]
Here is not a question forum. Use other places 

* [Discord](https://discord.gg/3tVdM5H8cC)Discord
* [GitHub Discussion](https://github.com/hajimehoshi/ebiten/discussions)
